#############################################################################
# Makefile for building: SampleApp
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  SampleApp.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile SampleApp.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -Isrc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SampleApp1.0.0
DISTDIR = /home/eli/Qt-Application-Startup-1/.tmp/SampleApp1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/model/dashboardmodel.cpp \
		src/model/prescriptionmodel.cpp \
		src/model/telemedicinemodel.cpp \
		src/model/appointmentmodel.cpp \
		src/model/doctorsearchmodel.cpp \
		src/model/confirmappointmentmodel.cpp \
		src/view/dashboardview.cpp \
		src/view/prescriptionview.cpp \
		src/view/telemedicineview.cpp \
		src/view/appointmentview.cpp \
		src/view/doctorsearchview.cpp \
		src/view/confirmappointmentview.cpp \
		src/controller/dashboardcontroller.cpp \
		src/controller/prescriptioncontroller.cpp \
		src/controller/appointmentcontroller.cpp \
		src/controller/doctorsearchcontroller.cpp \
		src/controller/confirmappointmentcontroller.cpp \
		src/controller/telemedicinecontroller.cpp qrc_resources.cpp \
		moc_mainwindow.cpp \
		moc_dashboardview.cpp \
		moc_prescriptionview.cpp \
		moc_telemedicineview.cpp \
		moc_appointmentview.cpp \
		moc_doctorsearchview.cpp \
		moc_confirmappointmentview.cpp \
		moc_dashboardcontroller.cpp \
		moc_prescriptioncontroller.cpp \
		moc_appointmentcontroller.cpp \
		moc_doctorsearchcontroller.cpp \
		moc_confirmappointmentcontroller.cpp \
		moc_telemedicinecontroller.cpp
OBJECTS       = main.o \
		mainwindow.o \
		dashboardmodel.o \
		prescriptionmodel.o \
		telemedicinemodel.o \
		appointmentmodel.o \
		doctorsearchmodel.o \
		confirmappointmentmodel.o \
		dashboardview.o \
		prescriptionview.o \
		telemedicineview.o \
		appointmentview.o \
		doctorsearchview.o \
		confirmappointmentview.o \
		dashboardcontroller.o \
		prescriptioncontroller.o \
		appointmentcontroller.o \
		doctorsearchcontroller.o \
		confirmappointmentcontroller.o \
		telemedicinecontroller.o \
		qrc_resources.o \
		moc_mainwindow.o \
		moc_dashboardview.o \
		moc_prescriptionview.o \
		moc_telemedicineview.o \
		moc_appointmentview.o \
		moc_doctorsearchview.o \
		moc_confirmappointmentview.o \
		moc_dashboardcontroller.o \
		moc_prescriptioncontroller.o \
		moc_appointmentcontroller.o \
		moc_doctorsearchcontroller.o \
		moc_confirmappointmentcontroller.o \
		moc_telemedicinecontroller.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		SampleApp.pro include/mainwindow.h \
		src/model/dashboardmodel.h \
		src/model/prescriptionmodel.h \
		src/model/telemedicinemodel.h \
		src/model/appointmentmodel.h \
		src/model/doctorsearchmodel.h \
		src/model/confirmappointmentmodel.h \
		src/view/dashboardview.h \
		src/view/prescriptionview.h \
		src/view/telemedicineview.h \
		src/view/appointmentview.h \
		src/view/doctorsearchview.h \
		src/view/confirmappointmentview.h \
		src/controller/dashboardcontroller.h \
		src/controller/prescriptioncontroller.h \
		src/controller/appointmentcontroller.h \
		src/controller/doctorsearchcontroller.h \
		src/controller/confirmappointmentcontroller.h \
		src/controller/telemedicinecontroller.h src/main.cpp \
		src/mainwindow.cpp \
		src/model/dashboardmodel.cpp \
		src/model/prescriptionmodel.cpp \
		src/model/telemedicinemodel.cpp \
		src/model/appointmentmodel.cpp \
		src/model/doctorsearchmodel.cpp \
		src/model/confirmappointmentmodel.cpp \
		src/view/dashboardview.cpp \
		src/view/prescriptionview.cpp \
		src/view/telemedicineview.cpp \
		src/view/appointmentview.cpp \
		src/view/doctorsearchview.cpp \
		src/view/confirmappointmentview.cpp \
		src/controller/dashboardcontroller.cpp \
		src/controller/prescriptioncontroller.cpp \
		src/controller/appointmentcontroller.cpp \
		src/controller/doctorsearchcontroller.cpp \
		src/controller/confirmappointmentcontroller.cpp \
		src/controller/telemedicinecontroller.cpp
QMAKE_TARGET  = SampleApp
DESTDIR       = 
TARGET        = SampleApp


first: all
####### Build rules

SampleApp:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SampleApp.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		SampleApp.pro \
		resources.qrc
	$(QMAKE) -o Makefile SampleApp.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
SampleApp.pro:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile SampleApp.pro

qmake_all: FORCE


all: Makefile SampleApp

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/mainwindow.h src/model/dashboardmodel.h src/model/prescriptionmodel.h src/model/telemedicinemodel.h src/model/appointmentmodel.h src/model/doctorsearchmodel.h src/model/confirmappointmentmodel.h src/view/dashboardview.h src/view/prescriptionview.h src/view/telemedicineview.h src/view/appointmentview.h src/view/doctorsearchview.h src/view/confirmappointmentview.h src/controller/dashboardcontroller.h src/controller/prescriptioncontroller.h src/controller/appointmentcontroller.h src/controller/doctorsearchcontroller.h src/controller/confirmappointmentcontroller.h src/controller/telemedicinecontroller.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/model/dashboardmodel.cpp src/model/prescriptionmodel.cpp src/model/telemedicinemodel.cpp src/model/appointmentmodel.cpp src/model/doctorsearchmodel.cpp src/model/confirmappointmentmodel.cpp src/view/dashboardview.cpp src/view/prescriptionview.cpp src/view/telemedicineview.cpp src/view/appointmentview.cpp src/view/doctorsearchview.cpp src/view/confirmappointmentview.cpp src/controller/dashboardcontroller.cpp src/controller/prescriptioncontroller.cpp src/controller/appointmentcontroller.cpp src/controller/doctorsearchcontroller.cpp src/controller/confirmappointmentcontroller.cpp src/controller/telemedicinecontroller.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) $(TARGET) $(OBJECTS) $(DESTDIR_TARGET) Makefile
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

clean: FORCE
	rm -rf $(OBJECTS_DIR)/*.o $(MOC_DIR)/*.cpp $(DESTDIR)$(TARGET) $(DESTDIR_TARGET)

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib/qt5/bin/rcc \
		resources/images/placeholder-logo-1.png
	/usr/lib/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_dashboardview.cpp moc_prescriptionview.cpp moc_telemedicineview.cpp moc_appointmentview.cpp moc_doctorsearchview.cpp moc_confirmappointmentview.cpp moc_dashboardcontroller.cpp moc_prescriptioncontroller.cpp moc_appointmentcontroller.cpp moc_doctorsearchcontroller.cpp moc_confirmappointmentcontroller.cpp moc_telemedicinecontroller.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_dashboardview.cpp moc_prescriptionview.cpp moc_telemedicineview.cpp moc_appointmentview.cpp moc_doctorsearchview.cpp moc_confirmappointmentview.cpp moc_dashboardcontroller.cpp moc_prescriptioncontroller.cpp moc_appointmentcontroller.cpp moc_doctorsearchcontroller.cpp moc_confirmappointmentcontroller.cpp moc_telemedicinecontroller.cpp
moc_mainwindow.cpp: include/mainwindow.h \
		src/controller/dashboardcontroller.h \
		src/model/dashboardmodel.h \
		src/view/dashboardview.h \
		src/controller/prescriptioncontroller.h \
		src/model/prescriptionmodel.h \
		src/view/prescriptionview.h \
		src/controller/telemedicinecontroller.h \
		src/model/telemedicinemodel.h \
		src/view/telemedicineview.h \
		src/controller/appointmentcontroller.h \
		src/model/appointmentmodel.h \
		src/view/appointmentview.h \
		src/controller/doctorsearchcontroller.h \
		src/model/doctorsearchmodel.h \
		src/view/doctorsearchview.h \
		src/view/confirmappointmentview.h \
		src/model/confirmappointmentmodel.h \
		src/controller/confirmappointmentcontroller.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/eli/Qt-Application-Startup-1/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/eli/Qt-Application-Startup-1 -I/home/eli/Qt-Application-Startup-1/include -I/home/eli/Qt-Application-Startup-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/mainwindow.h -o moc_mainwindow.cpp

moc_dashboardview.cpp: src/view/dashboardview.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/eli/Qt-Application-Startup-1/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/eli/Qt-Application-Startup-1 -I/home/eli/Qt-Application-Startup-1/include -I/home/eli/Qt-Application-Startup-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/view/dashboardview.h -o moc_dashboardview.cpp

moc_prescriptionview.cpp: src/view/prescriptionview.h \
		src/model/prescriptionmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/eli/Qt-Application-Startup-1/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/eli/Qt-Application-Startup-1 -I/home/eli/Qt-Application-Startup-1/include -I/home/eli/Qt-Application-Startup-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/view/prescriptionview.h -o moc_prescriptionview.cpp

moc_telemedicineview.cpp: src/view/telemedicineview.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/eli/Qt-Application-Startup-1/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/eli/Qt-Application-Startup-1 -I/home/eli/Qt-Application-Startup-1/include -I/home/eli/Qt-Application-Startup-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/view/telemedicineview.h -o moc_telemedicineview.cpp

moc_appointmentview.cpp: src/view/appointmentview.h \
		src/model/appointmentmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/eli/Qt-Application-Startup-1/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/eli/Qt-Application-Startup-1 -I/home/eli/Qt-Application-Startup-1/include -I/home/eli/Qt-Application-Startup-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/view/appointmentview.h -o moc_appointmentview.cpp

moc_doctorsearchview.cpp: src/view/doctorsearchview.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/eli/Qt-Application-Startup-1/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/eli/Qt-Application-Startup-1 -I/home/eli/Qt-Application-Startup-1/include -I/home/eli/Qt-Application-Startup-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/view/doctorsearchview.h -o moc_doctorsearchview.cpp

moc_confirmappointmentview.cpp: src/view/confirmappointmentview.h \
		src/model/confirmappointmentmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/eli/Qt-Application-Startup-1/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/eli/Qt-Application-Startup-1 -I/home/eli/Qt-Application-Startup-1/include -I/home/eli/Qt-Application-Startup-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/view/confirmappointmentview.h -o moc_confirmappointmentview.cpp

moc_dashboardcontroller.cpp: src/controller/dashboardcontroller.h \
		src/model/dashboardmodel.h \
		src/view/dashboardview.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/eli/Qt-Application-Startup-1/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/eli/Qt-Application-Startup-1 -I/home/eli/Qt-Application-Startup-1/include -I/home/eli/Qt-Application-Startup-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/controller/dashboardcontroller.h -o moc_dashboardcontroller.cpp

moc_prescriptioncontroller.cpp: src/controller/prescriptioncontroller.h \
		src/model/prescriptionmodel.h \
		src/view/prescriptionview.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/eli/Qt-Application-Startup-1/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/eli/Qt-Application-Startup-1 -I/home/eli/Qt-Application-Startup-1/include -I/home/eli/Qt-Application-Startup-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/controller/prescriptioncontroller.h -o moc_prescriptioncontroller.cpp

moc_appointmentcontroller.cpp: src/controller/appointmentcontroller.h \
		src/model/appointmentmodel.h \
		src/view/appointmentview.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/eli/Qt-Application-Startup-1/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/eli/Qt-Application-Startup-1 -I/home/eli/Qt-Application-Startup-1/include -I/home/eli/Qt-Application-Startup-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/controller/appointmentcontroller.h -o moc_appointmentcontroller.cpp

moc_doctorsearchcontroller.cpp: src/controller/doctorsearchcontroller.h \
		src/model/doctorsearchmodel.h \
		src/view/doctorsearchview.h \
		src/view/confirmappointmentview.h \
		src/model/confirmappointmentmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/eli/Qt-Application-Startup-1/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/eli/Qt-Application-Startup-1 -I/home/eli/Qt-Application-Startup-1/include -I/home/eli/Qt-Application-Startup-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/controller/doctorsearchcontroller.h -o moc_doctorsearchcontroller.cpp

moc_confirmappointmentcontroller.cpp: src/controller/confirmappointmentcontroller.h \
		src/model/confirmappointmentmodel.h \
		src/view/confirmappointmentview.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/eli/Qt-Application-Startup-1/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/eli/Qt-Application-Startup-1 -I/home/eli/Qt-Application-Startup-1/include -I/home/eli/Qt-Application-Startup-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/controller/confirmappointmentcontroller.h -o moc_confirmappointmentcontroller.cpp

moc_telemedicinecontroller.cpp: src/controller/telemedicinecontroller.h \
		src/model/telemedicinemodel.h \
		src/view/telemedicineview.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/eli/Qt-Application-Startup-1/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/eli/Qt-Application-Startup-1 -I/home/eli/Qt-Application-Startup-1/include -I/home/eli/Qt-Application-Startup-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/controller/telemedicinecontroller.h -o moc_telemedicinecontroller.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp include/mainwindow.h \
		src/controller/dashboardcontroller.h \
		src/model/dashboardmodel.h \
		src/view/dashboardview.h \
		src/controller/prescriptioncontroller.h \
		src/model/prescriptionmodel.h \
		src/view/prescriptionview.h \
		src/controller/telemedicinecontroller.h \
		src/model/telemedicinemodel.h \
		src/view/telemedicineview.h \
		src/controller/appointmentcontroller.h \
		src/model/appointmentmodel.h \
		src/view/appointmentview.h \
		src/controller/doctorsearchcontroller.h \
		src/model/doctorsearchmodel.h \
		src/view/doctorsearchview.h \
		src/view/confirmappointmentview.h \
		src/model/confirmappointmentmodel.h \
		src/controller/confirmappointmentcontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp include/mainwindow.h \
		src/controller/dashboardcontroller.h \
		src/model/dashboardmodel.h \
		src/view/dashboardview.h \
		src/controller/prescriptioncontroller.h \
		src/model/prescriptionmodel.h \
		src/view/prescriptionview.h \
		src/controller/telemedicinecontroller.h \
		src/model/telemedicinemodel.h \
		src/view/telemedicineview.h \
		src/controller/appointmentcontroller.h \
		src/model/appointmentmodel.h \
		src/view/appointmentview.h \
		src/controller/doctorsearchcontroller.h \
		src/model/doctorsearchmodel.h \
		src/view/doctorsearchview.h \
		src/view/confirmappointmentview.h \
		src/model/confirmappointmentmodel.h \
		src/controller/confirmappointmentcontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

dashboardmodel.o: src/model/dashboardmodel.cpp src/model/dashboardmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dashboardmodel.o src/model/dashboardmodel.cpp

prescriptionmodel.o: src/model/prescriptionmodel.cpp src/model/prescriptionmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prescriptionmodel.o src/model/prescriptionmodel.cpp

telemedicinemodel.o: src/model/telemedicinemodel.cpp src/model/telemedicinemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o telemedicinemodel.o src/model/telemedicinemodel.cpp

appointmentmodel.o: src/model/appointmentmodel.cpp src/model/appointmentmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o appointmentmodel.o src/model/appointmentmodel.cpp

doctorsearchmodel.o: src/model/doctorsearchmodel.cpp src/model/doctorsearchmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doctorsearchmodel.o src/model/doctorsearchmodel.cpp

confirmappointmentmodel.o: src/model/confirmappointmentmodel.cpp src/model/confirmappointmentmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o confirmappointmentmodel.o src/model/confirmappointmentmodel.cpp

dashboardview.o: src/view/dashboardview.cpp src/view/dashboardview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dashboardview.o src/view/dashboardview.cpp

prescriptionview.o: src/view/prescriptionview.cpp src/view/prescriptionview.h \
		src/model/prescriptionmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prescriptionview.o src/view/prescriptionview.cpp

telemedicineview.o: src/view/telemedicineview.cpp src/view/telemedicineview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o telemedicineview.o src/view/telemedicineview.cpp

appointmentview.o: src/view/appointmentview.cpp src/view/appointmentview.h \
		src/model/appointmentmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o appointmentview.o src/view/appointmentview.cpp

doctorsearchview.o: src/view/doctorsearchview.cpp src/view/doctorsearchview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doctorsearchview.o src/view/doctorsearchview.cpp

confirmappointmentview.o: src/view/confirmappointmentview.cpp src/view/confirmappointmentview.h \
		src/model/confirmappointmentmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o confirmappointmentview.o src/view/confirmappointmentview.cpp

dashboardcontroller.o: src/controller/dashboardcontroller.cpp src/controller/dashboardcontroller.h \
		src/model/dashboardmodel.h \
		src/view/dashboardview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dashboardcontroller.o src/controller/dashboardcontroller.cpp

prescriptioncontroller.o: src/controller/prescriptioncontroller.cpp src/controller/prescriptioncontroller.h \
		src/model/prescriptionmodel.h \
		src/view/prescriptionview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prescriptioncontroller.o src/controller/prescriptioncontroller.cpp

appointmentcontroller.o: src/controller/appointmentcontroller.cpp src/controller/appointmentcontroller.h \
		src/model/appointmentmodel.h \
		src/view/appointmentview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o appointmentcontroller.o src/controller/appointmentcontroller.cpp

doctorsearchcontroller.o: src/controller/doctorsearchcontroller.cpp src/controller/doctorsearchcontroller.h \
		src/model/doctorsearchmodel.h \
		src/view/doctorsearchview.h \
		src/view/confirmappointmentview.h \
		src/model/confirmappointmentmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doctorsearchcontroller.o src/controller/doctorsearchcontroller.cpp

confirmappointmentcontroller.o: src/controller/confirmappointmentcontroller.cpp src/controller/confirmappointmentcontroller.h \
		src/model/confirmappointmentmodel.h \
		src/view/confirmappointmentview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o confirmappointmentcontroller.o src/controller/confirmappointmentcontroller.cpp

telemedicinecontroller.o: src/controller/telemedicinecontroller.cpp src/controller/telemedicinecontroller.h \
		src/model/telemedicinemodel.h \
		src/view/telemedicineview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o telemedicinecontroller.o src/controller/telemedicinecontroller.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_dashboardview.o: moc_dashboardview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dashboardview.o moc_dashboardview.cpp

moc_prescriptionview.o: moc_prescriptionview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_prescriptionview.o moc_prescriptionview.cpp

moc_telemedicineview.o: moc_telemedicineview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_telemedicineview.o moc_telemedicineview.cpp

moc_appointmentview.o: moc_appointmentview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_appointmentview.o moc_appointmentview.cpp

moc_doctorsearchview.o: moc_doctorsearchview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_doctorsearchview.o moc_doctorsearchview.cpp

moc_confirmappointmentview.o: moc_confirmappointmentview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_confirmappointmentview.o moc_confirmappointmentview.cpp

moc_dashboardcontroller.o: moc_dashboardcontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dashboardcontroller.o moc_dashboardcontroller.cpp

moc_prescriptioncontroller.o: moc_prescriptioncontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_prescriptioncontroller.o moc_prescriptioncontroller.cpp

moc_appointmentcontroller.o: moc_appointmentcontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_appointmentcontroller.o moc_appointmentcontroller.cpp

moc_doctorsearchcontroller.o: moc_doctorsearchcontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_doctorsearchcontroller.o moc_doctorsearchcontroller.cpp

moc_confirmappointmentcontroller.o: moc_confirmappointmentcontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_confirmappointmentcontroller.o moc_confirmappointmentcontroller.cpp

moc_telemedicinecontroller.o: moc_telemedicinecontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_telemedicinecontroller.o moc_telemedicinecontroller.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/SampleApp/bin || mkdir -p $(INSTALL_ROOT)/opt/SampleApp/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/SampleApp/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/SampleApp/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/SampleApp/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/SampleApp/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

